<?php

use FirebdPHP\Firebird\Table\Table;

it("expect a query for a table of users with an auto generated primary key, an username and a unique phone number", function () {
    $query = Table::create(
        name: "users",
        columns: [
            "id" => [
                "type" => "int",
                "primary",
                "increment"
            ],
            "username" => [
                "type" => "varchar",
                "limit" => 150,
            ],
            "phone" => [
                "type" => "varchar",
                "limit" => 15,
                "unique"
            ]
        ]
    );

    $idealSqlQuery = "CREATE TABLE users (id int generated by default as identity primary key, username varchar(150) not null, phone varchar(15) not null unique)";

    expect($query)->toBe($idealSqlQuery);
});
